version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - CLAUDE_API_KEY=AIzaSyBxMR_UiyPHgeAZ99FUMUvj2IEd5dGK30M
      - MONGODB_URL=mongodb+srv://kishoresankarg23cse_db_user:1234%40sankar@cluster0.1cmrszx.mongodb.net/
      - DATABASE_NAME=meeting_notes_db
      - ENVIRONMENT=development
      - DEBUG=True
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000/api
    depends_on:
      - backend
    networks:
      - app-network
  
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - /var/jenkins_home/workspace/gmeet-pipeline/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - app-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  grafana-data:

